#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f ray_sphere_intersect.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ray_sphere_intersect.sv --exe ray_sphere_intersect_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vray_sphere_intersect.mk Vray_sphere_intersect

# run executable simulation file
obj_dir/Vray_sphere_intersect